// <auto-generated />
using System;
using Elevate.Profile.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elevate.Profile.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260710000547_ProfileIntialCreation")]
    partial class ProfileIntialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.NotificationSettings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("AchievementAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("MealReminders")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("WeeklyReports")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkoutReminders")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.PrivacySettings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("AllowDataSharing")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowProgressToFriends")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("PrivacySettings");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("DistanceUnit")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HeightUnit")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPremiumCached")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersProfile");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.NotificationSettings", b =>
                {
                    b.HasOne("Elevate.Profile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Elevate.Profile.Domain.Entities.NotificationSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.PrivacySettings", b =>
                {
                    b.HasOne("Elevate.Profile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("PrivacySettings")
                        .HasForeignKey("Elevate.Profile.Domain.Entities.PrivacySettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("Elevate.Profile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Preferences")
                        .HasForeignKey("Elevate.Profile.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("Elevate.Profile.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserProfileUserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UsersProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("Elevate.Profile.Domain.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<int>("UserProfileUserId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("UsersProfile");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Elevate.Profile.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("PrivacySettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
