// <auto-generated />
using System;
using Elevate.FitnessCalculation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elevate.FitnessCalculation.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(FitnessCalcDbContext))]
    partial class FitnessCalcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculatedMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CalculatedMetrics", (string)null);
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.ToTable("FitnessPlanConfigs", (string)null);
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserAssignedPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssignedPlans", (string)null);
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserFitnessStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserFitnessStats", (string)null);
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserPlanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForChange")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlanHistories", (string)null);
                });

            modelBuilder.Entity("CalculatedMetrics", b =>
                {
                    b.HasOne("Elevate.FitnessCalculation.Domain.Entities.UserFitnessStats", "UserFitnessStats")
                        .WithOne("CalculatedMetrics")
                        .HasForeignKey("CalculatedMetrics", "UserId")
                        .HasPrincipalKey("Elevate.FitnessCalculation.Domain.Entities.UserFitnessStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Elevate.FitnessCalculation.Domain.ValueObjects.MetabolicMetrics", "Metabolic", b1 =>
                        {
                            b1.Property<int>("CalculatedMetricsId")
                                .HasColumnType("int");

                            b1.Property<double>("Bmr")
                                .HasColumnType("float")
                                .HasColumnName("BMR");

                            b1.Property<double>("CalorieTarget")
                                .HasColumnType("float")
                                .HasColumnName("CalorieTarget");

                            b1.Property<double>("Tdee")
                                .HasColumnType("float")
                                .HasColumnName("TDEE");

                            b1.HasKey("CalculatedMetricsId");

                            b1.ToTable("CalculatedMetrics");

                            b1.WithOwner()
                                .HasForeignKey("CalculatedMetricsId");
                        });

                    b.Navigation("Metabolic")
                        .IsRequired();

                    b.Navigation("UserFitnessStats");
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.OwnsOne("Elevate.FitnessCalculation.Domain.ValueObjects.CaloriesRange", "caloriesRange", b1 =>
                        {
                            b1.Property<string>("FitnessPlanConfigPlanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("MaxCalorie")
                                .HasColumnType("float")
                                .HasColumnName("MaxCalories");

                            b1.Property<double>("MinCalorie")
                                .HasColumnType("float")
                                .HasColumnName("MinCalories");

                            b1.HasKey("FitnessPlanConfigPlanId");

                            b1.ToTable("FitnessPlanConfigs");

                            b1.WithOwner()
                                .HasForeignKey("FitnessPlanConfigPlanId");
                        });

                    b.OwnsOne("Elevate.FitnessCalculation.Domain.ValueObjects.PlanConfigration", "planConfigration", b1 =>
                        {
                            b1.Property<string>("FitnessPlanConfigPlanId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EstimatedDuration")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ProgramType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("WorkOutsperWeek")
                                .HasColumnType("int");

                            b1.HasKey("FitnessPlanConfigPlanId");

                            b1.ToTable("FitnessPlanConfigs");

                            b1.WithOwner()
                                .HasForeignKey("FitnessPlanConfigPlanId");
                        });

                    b.Navigation("caloriesRange")
                        .IsRequired();

                    b.Navigation("planConfigration")
                        .IsRequired();
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserAssignedPlans", b =>
                {
                    b.HasOne("Elevate.FitnessCalculation.Domain.Entities.FitnessPlanConfig", "plan")
                        .WithMany("Plans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plan");
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserFitnessStats", b =>
                {
                    b.OwnsOne("Elevate.FitnessCalculation.Domain.ValueObjects.BodyMetrics", "BodyMetrics", b1 =>
                        {
                            b1.Property<int>("UserFitnessStatsId")
                                .HasColumnType("int");

                            b1.Property<int>("Age")
                                .HasColumnType("int")
                                .HasColumnName("Age");

                            b1.Property<double>("Height")
                                .HasColumnType("float")
                                .HasColumnName("Height");

                            b1.Property<double>("Weight")
                                .HasColumnType("float")
                                .HasColumnName("Weight");

                            b1.HasKey("UserFitnessStatsId");

                            b1.ToTable("UserFitnessStats");

                            b1.WithOwner()
                                .HasForeignKey("UserFitnessStatsId");
                        });

                    b.Navigation("BodyMetrics")
                        .IsRequired();
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Elevate.FitnessCalculation.Domain.Entities.UserFitnessStats", b =>
                {
                    b.Navigation("CalculatedMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
