// <auto-generated />
using System;
using Elevate.Progress.Infrastructure.Persistence.ProgressDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elevate.Progress.Migrations
{
    [DbContext(typeof(ProgressDbContext))]
    [Migration("20260712151628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements", t =>
                        {
                            t.HasCheckConstraint("CK_Achievement_RequiredValue", "RequiredValue >= 0");
                        });
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.Streak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastWorkoutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Streaks", t =>
                        {
                            t.HasCheckConstraint("CK_Streak_CurrentStreak", "CurrentStreak >= 0");

                            t.HasCheckConstraint("CK_Streak_LongestStreak", "LongestStreak >= 0");
                        });
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.UserStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<int>("TotalCaloriesBurned")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalWeightLost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalWorkoutDuration")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkouts")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserStatistics", t =>
                        {
                            t.HasCheckConstraint("CK_UserStatistics_CurrentStreak", "CurrentStreak >= 0");

                            t.HasCheckConstraint("CK_UserStatistics_LongestStreak", "LongestStreak >= 0");

                            t.HasCheckConstraint("CK_UserStatistics_TotalCaloriesBurned", "TotalCaloriesBurned >= 0");

                            t.HasCheckConstraint("CK_UserStatistics_TotalWeightLost", "TotalWeightLost >= 0");

                            t.HasCheckConstraint("CK_UserStatistics_TotalWorkoutDuration", "TotalWorkoutDuration >= 0");

                            t.HasCheckConstraint("CK_UserStatistics_TotalWorkouts", "TotalWorkouts >= 0");
                        });
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.WeightHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("WeightHistory", t =>
                        {
                            t.HasCheckConstraint("CK_WeightHistory_Weight", "Weight >= 40 AND Weight <= 200");
                        });
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLogs", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutLog_CaloriesBurned", "CaloriesBurned >= 0");

                            t.HasCheckConstraint("CK_WorkoutLog_Duration", "Duration >= 0");

                            t.HasCheckConstraint("CK_WorkoutLog_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.WorkoutLogExercises", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutLogId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLogExercises");
                });

            modelBuilder.Entity("Elevate.Progress.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("char(36)");

                    b.HasKey("SessionId");

                    b.ToTable("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
